### ISSUE TITLE
Preflight options / access-control-allow-origin

### ISSUE THREAD

**Issue by Rodeoclash** [basicallydan/interfake#36]
I might be missing something in the docs but it seems their is no way of handling pre-flight OPTIONS requests? In particular a CORs request to the API.

Unless I'm missing something obvious I'm happy to add this functionality.

**Comment by basicallydan** [comment]
Hey @Rodeoclash you're quite right, OPTIONS isn't supported at the moment. To be honest, I completely forgot about it because originally Interfake was using express more directly so it just came for free. Now it barely uses any express features. If you want to implement it I'd be happy to accept a PR :)

**Comment by basicallydan** [comment]
Alright, this should be supported now in 1.16.0 automatically :) @Rodeoclash let me know if anything isn't working here!
