### ISSUE TITLE
createRoute() has issues with the param property in the request json

### ISSUE THREAD

**Issue by rotovibe** [basicallydan/interfake#46]
In the example wiki, this snippet is causing a 404 when GETting the resource:

interfake.createRoute({
    request: {
        url: '/whats-next',
        method: 'get',
        query: { // Optional querystring parameters
            page: 2
        }
    },
    response: {
        code: 200, // HTTP Status Code
        delay: 50, // Delay in milliseconds
        body: { // JSON Body Response
            next:'more stuff'
        },
        headers: { // Optional headers
            'X-Powered-By': 'Interfake'
        }
    }
});

It seems to work when I take the query property out of the request graph.

**Comment by basicallydan** [comment]
Hey @rotovibe! Thanks for raising this.

Can you show me the request you're making?

**Comment by rotovibe** [comment]
http://localhost:3000/whats-next
I get a 404.
I took out the query property in the request route definition json and it seemed to work fine.

I also noticed this issue...I still have the query property excluded in the request defintion. But when I add a querystring...
http://localhost:3000/whats-next/?page=2
and
http://localhost:3000/whats-next?page=2
I get a 404 as well.

thanks for looking into it.

**Comment by basicallydan** [comment]
Hey @rotovibe – all of this is by design. Interfake is pretty strict about endpoint definitions. So in your request definition, if the querystring is there you need to include it in your request. If it's not, you should not include it.

Here's an example.

```
interfake.createRoute({
    request: {
        url: '/whats-next',
        method: 'get',
        query: { // Optional querystring parameters
            page: 2
        }
    },
...
```

For the above request, you _must_ use `/whats-next?page=2` to get a response.

Is this against your expectations? Is the reason for your confusion the comment `// Optional querystring parameters`?

**Comment by rotovibe** [comment]
Perfect. Thanks for the info @basicallydan . Makes sense.

**Comment by basicallydan** [comment]
Cheers @rotovibe, no problem 👍
